import { memo } from 'react';
import Head from 'next/head';

const SEO: React.VFC = () => {
  return (
    <Head>
      <title>Cook Clip</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='og:title' content='Cook Clip' />
      <meta name='description' content='clip cooking video' />
      <meta property='og:description' content='clip cooking video' />
      <meta property='og:image' content='https://cook-clip.vercel.app/cooking_mama.png' />
      <meta name='twitter:card' content='summary_large_image' />
      <link
        rel='icon'
        href='data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text x=%2250%%22 y=%2250%%22 style=%22dominant-baseline:central;text-anchor:middle;font-size:90px;%22>🐧</text></svg>'
      />
      <link
        rel='icon alternate'
        type='image/png'
        href='https://twemoji.maxcdn.com/v/13.1.0/72x72/1f427.png'
      />
    </Head>
  );
};

export default memo(SEO);
